name: ci
on: [push]
jobs:
  ci_pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      
      - name: install npm modules
        run: npm install
        
      - name: run ESLint
        run: npm run lint
        
      - name: run format check
        run: npm run format:check
        
      - name: unit tests
        run: npm run test
