name: cd
on: [push]
permissions:
  packages: write

env:
  NODE_VERSION: 18.14.2
  REGISTRY: ghcr.io
  IMAGE_NAME: ci-cd-dhbw-hdh-pschoeppner/tim.knittel/klausur
  CONTAINER_NAME: ${{ github.event.repository.name }}
  IMAGE_VERSION: 0.1.0

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Get project version
        run: >
          echo "PROJECT_VERSION=$(
            npm run env | grep "^npm_package_version=" | cut -d'=' -f2
          )" >> $GITHUB_ENV
          && source $GITHUB_ENV
          && echo $PROJECT_VERSION

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Svelte check
        run: npm run check

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/ci-cd-dhbw-hdh-pschoeppner/tim.knittel/klausur:${{ env.PROJECT_VERSION }}
